name: plaidml-keras
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    #- python==3.5.2
    - python==3.6
    - pip
    - numpy
    - matplotlib
    #- jupyter
    - opencv
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn==0.10.0
    - pandas==0.22
    - ffmpeg
    #- imageio=2.1.2
    - imageio
    #- pyqt=4.11.4
    - pip:
        - moviepy
        #- opencv-python
        - tensorflow==1.14.0
        - plaidml-keras
